### ISSUE TITLE
Hard-coded string "last variant" cannot be translated

### ISSUE THREAD

**Issue by dinism** [moodleou/moodle-qtype_varnumericset#23]
Hi
Maybe this is not the place to do this.
I'm PT-PT translator and i found that the text "last variant" are not in AMOS.

Is it possible to put this like a string to translate?
TIA

**Comment by timhunt** [comment]
This is the right place to do this, and this is a bug (sorry).

**Comment by timhunt** [comment]
Acutally, while that form field is added to the form, it is always hidden. (Which is an odd way to do things, but ...)

So, I don't think there is any need to translate that string. Have you ever seen it visible in the user-interface?

**Comment by dinism** [comment]
I can see it as teacher  and all up roles
![imagem](https://user-images.githubusercontent.com/14828021/50299327-3ba90f80-0479-11e9-8797-f8cd36aa1ac1.png)

**Comment by timhunt** [comment]
Judging by what I see in our theme, the bug is that that is visible. It should not be.

**Comment by dinism** [comment]
Using the Boost theme.

**Comment by timhunt** [comment]
Thank you for reporting this. Howver, when I try the latest version of this plugin in Boost, I cannot see that string, as expected. So, closing this.
