### ISSUE TITLE
Behat tests failing - basic_test.feature

### ISSUE THREAD

**Issue by AdilIqbal95** [moodleou/moodle-qtype_varnumericset#28]
Hi, the test stated above is failing.

**Environment details:**
MySQL 5.7
PHP 7.4
Moodle latest MOODLE_400_STABLE

**Error details:**
**Scenario: Create, edit then preview a variable numeric sets question.**
And I switch to "questionpreview" window: Unable to locate window: questionpreview (Facebook\WebDriver\Exception\NoSuchWindowException)

**Scenario: Create, edit then preview a variable numeric set with units question.**
And I switch to "questionpreview" window: Unable to locate window: questionpreview (Facebook\WebDriver\Exception\NoSuchWindowException)

**Comment by AdilIqbal95** [comment]
Thanks for your response. Unfortunately I don't currently have capacity to do so but will try to when I do.

**Comment by timhunt** [comment]
I've  just pushed the latest code from the OU repository. Tests are passing now.
